{
 "title": "WE-node",
 "time": { "from": "2024-05-09T08:28:57.287Z", "to": "2024-05-09T08:43:30.171Z" },
 "templating": {
  "list": [
   {
    "name": "WINDOW_BLOCKS",
    "label": "WINDOW_BLOCKS",
    "query": "5, 10, 15, 20, 25, 30, 35, 40, 45, 50"
   },
   {
    "name": "WINDOW_TIME",
    "label": "WINDOW_TIME",
    "query": "10s, 30s, 1m, 2m, 3m, 4m, 5m, 6m"
   },
   {
    "name": "WINDOW_10S",
    "label": "WINDOW_10S",
    "query": "1, 3, 6, 12, 18, 24, 30, 36, 42"
   }
  ]
 },
 "panels": [
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "block",
     "query": "data = from(bucket: \"we/autogen\") \n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"block\" and\nr._field == \"height\"\n)\n|> yield()",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "event::tag", "operator": "=", "value": "Mined" }
     ]
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "block_timestamp",
     "select": [
      [
       { "params": [ "node" ], "type": "field" },
       { "params": [ "1s" ], "type": "elapsed" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Tx Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "txs.moving_average",
     "groupBy": [
      { "params": [ "8s" ], "type": "time" }
     ],
     "measurement": "block",
     "query": "data = from(bucket: \"we/autogen\") \n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"block\" and\nr._field == \"height\"\n)\n|> yield()",
     "select": [
      [
       { "params": [ "txs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$WINDOW_BLOCKS" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "event::tag", "operator": "=", "value": "Mined" }
     ]
    },
    {
     "alias": "block.txs",
     "groupBy": [
      { "params": [ "8s" ], "type": "time" }
     ],
     "measurement": "block",
     "query": "data = from(bucket: \"we/autogen\") \n|> range(start: -1h)\n|> filter(fn: (r) => r._measurement == \"block\" and\nr._field == \"height\"\n)\n|> yield()",
     "select": [
      [
       { "params": [ "txs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "event::tag", "operator": "=", "value": "Mined" }
     ]
    }
   ]
  },
  {
   "title": "Utx Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "utx-pool-size",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    }
   ]
  },
  {
   "title": "Tx Confirmation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "alias": "conflicts",
     "measurement": "mvcc-conflict-counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "$WINDOW_10S" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    },
    {
     "alias": "confirmed",
     "measurement": "tx-confirmatory.confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "$WINDOW_10S" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    },
    {
     "alias": "validation errors",
     "measurement": "invalid-proofs-count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "$WINDOW_10S" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "host.cpu",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "mode::tag", "operator": "=", "value": "user" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    }
   ]
  },
  {
   "title": "Validation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "validation errors",
     "measurement": "invalid-proofs-count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    },
    {
     "alias": "confirmed",
     "measurement": "tx-confirmatory.confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "measurement": "host.memory",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" },
      { "condition": "AND", "key": "mode::tag", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Conflict Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "conflicts",
     "measurement": "mvcc-conflict-counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    },
    {
     "alias": "confirmed",
     "measurement": "tx-confirmatory.confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "node-0" }
     ]
    }
   ]
  }
 ]
}